### ISSUE TITLE
Gateway remains active when underlying session is closed by host

### ISSUE THREAD

**Issue by tpitale** [net-ssh/net-ssh-gateway#11]
In a scenario where I have 3 computers, A, B, and C. A is the origin, B is the tunnel, C is the destination.

If I connect to C, from A, through B, there is an instance of `Gateway`, and that `gateway` has a `session` instance variable.

If, for some reason, B or C decides to close that SSH connection (e,g,, a server restart), the `gateway` instance used in code on server A remains `@active == true`. To my code, the tunnel should appears to still be operating correctly. To any code that was using that tunnel, there is simply no communication/data being transferred, but no way to know that the connection has _actually_ been closed.

**Comment by tpitale** [comment]
To reproduce, start irb on a server … make a gateway/tunnel to another server.

Then, directly connect to the destination server. Kill the SSH connection there, or otherwise disrupt that server.

In my experience, code using that tunnel will "hang" forever, for lack of a better term. Specifically, `psql` connections made to databases on the destination server.

**Comment by mfazekas** [comment]
code:
```ruby
require 'net/ssh'
gateway = Net::SSH::Gateway.new('localhost', ENV['user'], verbose: :debug)

def start_server
  server = TCPServer.open(0)
  Thread.start do
    loop do
      Thread.start(server.accept) do |client|
        begin
          client.puts "Hello\n"
          sleep 60
          client.puts "End of wait => close\n"
          client.close
        rescue
          puts "Error in server:#{$!}"
          raise
        end
      end
    end
  end
  server
end

s = start_server

begin
  gateway.open 'localhost', s.addr[1] do |local_port|
    client = TCPSocket.new('localhost', local_port)
    data = client.read(5)
    puts "Data1:#{data}"
    data = client.read(5)
    puts "Data2:#{data}"
    client.close()
  end
rescue Exception => e
  puts e.message
end

gateway.shutdown!
```

This happens:
```sh
Data1:Hello
# kill sshd to close the connection
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 1 clearing O_NONBLOCK
Transferred: sent 7764, received 6640 bytes, in 18.2 seconds
Bytes per second: sent 426.6, received 364.8
debug1: Exit status 0
... (net-ssh-gateway hangs)
```

**Comment by tpitale** [comment]
Clever. That appears to simulate the issue. Thanks!

**Comment by mfazekas** [comment]
As a workaround you should be able to use
```ruby
Thread.abort_on_exception = true
```
for now.
It will be handled in https://github.com/net-ssh/net-ssh/issues/339

**Comment by mfazekas** [comment]
This should be fixed in net-ssh 4.0.0.alpha2 can you please verify?

**Comment by tpitale** [comment]
I'm dealing with an issue with chef requiring net-ssh ~> 2.6.

I'll let you know if I figure out a way around that. Yayyyy dependency fun.

**Comment by tpitale** [comment]
Okay. Split my Gemfile out so chef and capistrano can just be for local work. Fun times.

Deploying now for testing.

**Comment by tpitale** [comment]
Well, it doesn't _break_ anything, so far. I cannot yet confirm if it fixes the problem, but looks good to me! I'd say close this one as fixed.

Thanks @mfazekas!
