### ISSUE TITLE
Please cut a new gem release to include :loop_wait fix

### ISSUE THREAD

**Issue by bobziuchkovski** [net-ssh/net-ssh-gateway#13]
I noticed the latest gem release, v1.2.0, falls over when you specify the `:loop_wait` option.  It appears this is fixed in `master`.  Could you cut a new v1.2.1 release that includes this fix?  For our use case this will help us to drastically reduce the CPU cycles used by net-ssh/net-ssh-gateway.  Thanks!

**Comment by delano** [comment]
I pushed two new releases: 1.3.0 and 2.0.0 from the latest master branch. Functionally the same but 2.0.0 requires net-ssh 4 or greater which means Ruby 1.9 support is dropped.

**Comment by bobziuchkovski** [comment]
Thank you very much!
