### ISSUE TITLE
ERROR:  While executing gem ... (Gem::Security::Exception)

### ISSUE THREAD

**Issue by krmannix** [net-ssh/net-ssh-gateway#14]
Following the steps to install with `HighSecurity` trust policy results in the following error:

```
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=netssh/DC=solutious/DC=com not valid after 2017-12-15 18:05:22 UTC
```

**Comment by bf4** [comment]
practically speaking the gem security isn't really that well used and shouldn't keep you from using it.  I used to sign my gems and stopped. I even wrote the gems security guide. Go figure.  Close as stale?

**Comment by krmannix** [comment]
Closing as stale - thanks!
