### ISSUE TITLE
Gateway becomes unusable after failed communication

### ISSUE THREAD

**Issue by zeroem** [net-ssh/net-ssh-gateway#4]
I created a repo to demonstrate the issue, https://github.com/zeroem/net-ssh-gateway-bug .

The synopsis is:
  - Create an ssh gateway
  - Open a tunnel to a nonexistent service (ie nothing listening on the given host/port)
  - Try to communicate over the tunnel
  - Request times out.
  - Any further requests over the same gateway, even to existing services, will also timeout

**Comment by thechile** [comment]
I have this same problem... if i establish a gateway connection and then try to connect to a server whose hostname fails to resolve, via the gateway, then the underlying gateway session is terminated and subsequent connection via the gateway fail with timeout.

**Comment by doprdele** [comment]
Has this been merged back into net-ssh?

**Comment by thechile** [comment]
Not yet.. Still trying to get time to write tests and demo problem to avoid future regressions. Hopefully get that done soon and get these changes merged.

**Comment by mfazekas** [comment]
FYI this should be fixed in net-ssh 3.10.0beta3
