### ISSUE TITLE
Detecting closing of underlying session connection

### ISSUE THREAD

**Issue by tpitale** [net-ssh/net-ssh-gateway#7]
There does not appear to be an effective way to know if the tunnel was closed/disconnected by the remote host.

For example, `active?` still shows as true (which is likely an unintended purpose). But, it would be great if there was a way to know if the connection was actually closed, probably by passing some information up from the underlying net-ssh.

**Comment by tpitale** [comment]
It seems like checking for `@session.closed?` in this loop: https://github.com/net-ssh/net-ssh-gateway/blob/master/lib/net/ssh/gateway.rb#L196-L201 could be the start of detecting a closed connection.

If @delano or @jamis have any perspective on how to then alert the gateway, I'd be happy to send a PR.

**Comment by tpitale** [comment]
Could be as simple as adding a method on the gateway instance to check for `@session.closed?`, leave it up to the user to watch for closed connections.

**Comment by mfazekas** [comment]
Can you detail the concrete usecase?

**Comment by tpitale** [comment]
Servers A, B, and C. A => B => C, with B acting as a tunnel/gateway. If B or C close the connection from their end, there does not appear to be away to ask the ruby gateway instance if the connection is still active, to take action (like restarting a process or killing a DB connection).

**Comment by mfazekas** [comment]
Thanks. Net-ssh-gateway is in maitanance mode, and AFAIK we have no plans to extend it to support your usecase.
You should be able to subclass Gateway and get access to ```@session``` but it's tricky business because of the locking, another option might be forking the library. Then we can discuss if/in what way we can integrate those changes.

**Comment by tpitale** [comment]
I can send a PR @mfazekas.
