### ISSUE TITLE
Reverse tunnel support

### ISSUE THREAD

**Issue by barttenbrinke** [net-ssh/net-ssh-gateway#8]
I am working on a project that needs to setup reverse SSH tunnels, for example:
```
ssh -g -N -R 172.17.0.1:3006:127.0.0.1:3006 root@123.123.123.123
```
I'd love to create a pull request for this, but as it it is, I have no clue as to where to start :)
Help :question:

**Comment by mfazekas** [comment]
You should be able to use remote on net-ssh. 
```ruby
Net::SSH.start("host", "user", :password => "password") do |ssh|
  ssh.forward.remote(80, "www.google.com", 1234)
  ssh.loop { true }
end
```
